# -----------------------------
# I2C Support
# -----------------------------
CONFIG_I2C=y
CONFIG_I2C_NRFX=y

# -----------------------------
# Logging (optional but recommended)
# -----------------------------
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# -----------------------------
# Thread stack (UBX parsing needs some room)
# -----------------------------
CONFIG_MAIN_STACK_SIZE=4096

# -----------------------------
# Enable printk (for debugging)
# -----------------------------
CONFIG_PRINTK=y
CONFIG_STDOUT_CONSOLE=y

# -----------------------------
# Enable Bluetooth
# -----------------------------
CONFIG_BT=y
CONFIG_BT_OBSERVER=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_ZEPHYR_NUS=y

# change MTU to 247 bytes (max) to allow longer strings to be sent
# default MTU is 23
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_L2CAP_TX_MTU=247
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251
